sudo: required
services:
  - docker

before_install:
  - docker build -t omnistat/react-test -f ./client/Dockerfile.dev ./client # Only the dev file will allow tests 

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t omnistat/multi-client ./client
  - docker build -t omnistat/multi-nginx ./nginx
  - docker build -t omnistat/multi-server ./server
  - docker build -t omnistat/multi-worker ./worker

# Login to dockerhub cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push images to dockerhub
  - docker push omnistat/multi-client
  - docker push omnistat/multi-nginx
  - docker push omnistat/multi-server
  - docker push omnistat/multi-worker