sudo: required
services:
  - docker

before_install:
  - docker build -t omnistat/react-test -f ./client/Dockerfile.dev ./client # Only the dev file will allow tests 

script:
  - docker run omnistat/react-test npm test -- --coverage

after_success:
  - docker build -t omnistat/multi-client ./client
  - docker build -t omnistat/multi-nginx ./nginx
  - docker build -t omnistat/multi-server ./server
  - docker build -t omnistat/multi-worker ./worker


  script:
  - docker run -e CI=true USERNAME/react-test npm test